"""Interactive setup wizard for Agentcy.

Goal: one command that
- asks for the Azure Foundry + GitHub values needed to connect and open a PR
- tells you where to find each value
- optionally writes packages/agentcy/.env (do NOT commit secrets)

Run:
    ./.venv/bin/python packages/agentcy/scripts/setup_wizard.py
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
AGENTCY_DIR = REPO_ROOT / "packages" / "agentcy"
ENV_EXAMPLE = AGENTCY_DIR / ".env.example"
ENV_FILE = AGENTCY_DIR / ".env"


def _prompt(label: str, help_text: str, default: str | None = None, secret: bool = False) -> str:
    print("\n" + label)
    print("  Where to find it:")
    for line in help_text.strip().splitlines():
        print(f"  - {line.strip()}")
    if default:
        prompt = f"Enter value (default: {default}): "
    else:
        prompt = "Enter value: "

    # Keep it simple: avoid getpass so it works everywhere; just don't echo the value back.
    value = input(prompt).strip()
    if not value and default is not None:
        value = default
    if secret and value:
        print("  (captured; not printing secrets)")
    return value


def _yes_no(prompt: str, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    ans = input(f"{prompt} {suffix}: ").strip().lower()
    if not ans:
        return default
    return ans in {"y", "yes"}


def _write_env(values: dict[str, str]) -> None:
    lines: list[str] = []
    lines.append("# Generated by packages/agentcy/scripts/setup_wizard.py")
    lines.append("# Do NOT commit secrets. This file should stay local.")
    lines.append("")
    for k, v in values.items():
        lines.append(f"{k}={v}")
    lines.append("")
    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")


def _run(cmd: list[str]) -> int:
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    return int(result.returncode)


def main() -> int:
    print("Agentcy setup wizard")
    print(f"Repo root: {REPO_ROOT}")
    print(f"Env template: {ENV_EXAMPLE}")

    if not ENV_EXAMPLE.exists():
        print("ERROR: Missing packages/agentcy/.env.example")
        return 2

    print("\nThis will help you connect Azure Foundry and open a GitHub PR.")
    print("You will need: Azure Foundry project endpoint + model deployment name + auth, plus a GitHub token.")

    default_endpoint = "https://edw-resource.services.ai.azure.com/api/projects/edw"
    user_endpoint = _prompt(
        "USER_ENDPOINT",
        "Azure AI Foundry / Azure AI Projects portal → open your Project → look for 'Project endpoint' (API endpoint).\n"
        "It looks like: https://<resource>.services.ai.azure.com/api/projects/<project>",
        default=default_endpoint,
    )

    model_deployment = _prompt(
        "MODEL_DEPLOYMENT_NAME",
        "Azure AI Foundry portal → your Project → Deployments → copy the deployment name you want the agent to use.",
        default="gpt-4.1-mini",
    )

    auth_mode = _prompt(
        "Auth mode",
        "Choose how the scripts authenticate to Foundry:\n"
        "- project_key: easiest for local testing (set PROJECT_API_KEY)\n"
        "- service_principal: better for automation (set AZURE_CLIENT_ID/TENANT_ID/CLIENT_SECRET)",
        default="project_key",
    ).lower()

    project_api_key = ""
    azure_client_id = ""
    azure_tenant_id = ""
    azure_client_secret = ""

    if auth_mode in {"project_key", "key", "api_key"}:
        project_api_key = _prompt(
            "PROJECT_API_KEY",
            "Azure AI Foundry portal → your Project → Settings/Keys (Project API key).\n"
            "Copy the Project API key (keep it secret).",
            secret=True,
        )
    else:
        azure_client_id = _prompt(
            "AZURE_CLIENT_ID",
            "Azure Portal → Microsoft Entra ID → App registrations → your app → Overview → Application (client) ID.",
            secret=True,
        )
        azure_tenant_id = _prompt(
            "AZURE_TENANT_ID",
            "Azure Portal → Microsoft Entra ID → Overview → Tenant ID.",
            secret=True,
        )
        azure_client_secret = _prompt(
            "AZURE_CLIENT_SECRET",
            "Azure Portal → Microsoft Entra ID → App registrations → your app → Certificates & secrets → Client secrets → Value.",
            secret=True,
        )

    github_repo = _prompt(
        "Target GitHub repo (owner/repo)",
        "This is the GitHub repository where the PR will be opened.\n"
        "Example for this workspace: edwinestro/edwinestro.github.io",
        default="edwinestro/edwinestro.github.io",
    )

    github_token = _prompt(
        "GITHUB_TOKEN",
        "GitHub → Settings → Developer settings → Personal access tokens (fine-grained).\n"
        "Grant access to the target repo and enable: Repository permissions → Issues: Read/Write, Pull requests: Read/Write, Contents: Read/Write.",
        secret=True,
    )

    print("\nNext commands (copy/paste)")
    print("1) Create env file (optional)")
    print(f"   cp {ENV_EXAMPLE} {ENV_FILE}")
    print("   # then paste the values the wizard collected")

    should_write = _yes_no(f"Write {ENV_FILE} now with these values?", default=False)
    if should_write:
        _write_env(
            {
                "USER_ENDPOINT": user_endpoint,
                "MODEL_DEPLOYMENT_NAME": model_deployment,
                "PROJECT_API_KEY": project_api_key,
                "AZURE_CLIENT_ID": azure_client_id,
                "AZURE_TENANT_ID": azure_tenant_id,
                "AZURE_CLIENT_SECRET": azure_client_secret,
                "GITHUB_ISSUES_REPO": github_repo,
                "GITHUB_TOKEN": github_token,
            }
        )
        print(f"Wrote {ENV_FILE}")

    print("\n2) Load env vars")
    print("   set -a && source packages/agentcy/.env && set +a")

    print("\n3) Verify Azure Foundry connection")
    print("   ./.venv/bin/python packages/agentcy/scripts/foundry_smoke_test.py")

    print("\n4) Raise a PR that adds hello-world.txt (dry-run first)")
    print(
        "   ./.venv/bin/python packages/agentcy/scripts/foundry_to_github_pr.py \\\n"
        "     --repo "
        + github_repo
        + " \\\n"
        "     --base main \\\n"
        "     --allow-prefix ./ \\\n"
        "     --feedback \"Create a new file hello-world.txt at repo root containing exactly: Hello world\" \\\n"
        "     --dry-run"
    )

    print("\n5) If the proposal looks good, run without --dry-run to open the PR.")
    print("\nWhere things live in this repo")
    print("- Env template: packages/agentcy/.env.example")
    print("- Connection test: packages/agentcy/scripts/foundry_smoke_test.py")
    print("- PR creator: packages/agentcy/scripts/foundry_to_github_pr.py")

    if not user_endpoint or not model_deployment:
        print("\nWARNING: USER_ENDPOINT and/or MODEL_DEPLOYMENT_NAME were blank.")

    if should_write and _yes_no("Run the Foundry smoke test now?", default=True):
        # Load env vars into this process by passing them explicitly.
        env = {
            "USER_ENDPOINT": user_endpoint,
            "MODEL_DEPLOYMENT_NAME": model_deployment,
        }
        if project_api_key:
            env["PROJECT_API_KEY"] = project_api_key
        if azure_client_id and azure_tenant_id and azure_client_secret:
            env["AZURE_CLIENT_ID"] = azure_client_id
            env["AZURE_TENANT_ID"] = azure_tenant_id
            env["AZURE_CLIENT_SECRET"] = azure_client_secret

        print("\nRunning smoke test...")
        rc = subprocess.run(
            [sys.executable, "packages/agentcy/scripts/foundry_smoke_test.py"],
            cwd=str(REPO_ROOT),
            env={**dict(os.environ), **env} if "os" in globals() else None,
        ).returncode
        if rc != 0:
            print("Smoke test failed. Fix the env vars above and retry.")
            return int(rc)

        if _yes_no("Generate a PR proposal (dry-run) to add hello-world.txt?", default=True):
            print("\nGenerating PR proposal (dry-run)...")
            cmd = [
                sys.executable,
                "packages/agentcy/scripts/foundry_to_github_pr.py",
                "--repo",
                github_repo,
                "--base",
                "main",
                "--allow-prefix",
                "./",
                "--feedback",
                "Create a new file hello-world.txt at repo root containing exactly: Hello world",
                "--dry-run",
            ]
            rc2 = subprocess.run(cmd, cwd=str(REPO_ROOT), env={**dict(os.environ), **env}).returncode
            if rc2 != 0:
                return int(rc2)
            print("\nDry-run complete. Inspect packages/agentcy/generated/pr_proposal.json")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
